version: "3.9"
volumes:
  freshrss-data:
  freshrss-extensions:
  better-rss-data:

services:
  freshrss:
    image: freshrss/freshrss
    container_name: freshrss
    ports:
      - 9900:80
    environment:
      - CRON_MIN=4,34
      - TZ=Asia/Kolkata
    volumes:
      - freshrss-data:/var/www/FreshRSS/data
      - freshrss-extensions:/var/www/FreshRSS/extensions
    links:
      - better-rss
    restart: unless-stopped
  better-rss:
    build: .
    container_name: better-rss
    volumes:
      - better-rss-data:/opt/better-rss/data
    restart: unless-stopped