# Generated by Django 3.1.3 on 2020-11-25 15:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RssFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=512)),
                ('feed_url', models.CharField(max_length=512)),
                ('should_update_summary', models.BooleanField(default=True)),
                ('nick_name', models.CharField(max_length=16)),
                ('refresh_interval_minutes', models.IntegerField(default=60)),
                ('last_update', models.DateTimeField(default=datetime.datetime(1999, 12, 30, 18, 30, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='RssItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=512)),
                ('published', models.CharField(max_length=128)),
                ('image', models.CharField(max_length=512)),
                ('summary', models.CharField(max_length=2048)),
                ('nlp_summary', models.CharField(max_length=2048)),
                ('author', models.CharField(max_length=512)),
                ('save_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rss_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betterRss.rssfeed')),
            ],
        ),
    ]
