# Generated by Django 3.1.3 on 2021-01-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betterRss', '0002_auto_20210102_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssitem',
            name='link',
            field=models.CharField(db_index=True, max_length=512),
        ),
    ]
